name: Workflow of exercise 1
run-name: First workflow # Optional

# Events triggering the workflow
on: 
  workflow_dispatch:

# Group of jobs to run as part of the workflow
permissions:
  contents: read
  artifact-metadata: read
  packages: read
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello world"