name: Workflow of exercise 3
run-name: Third workflow - vars # Optional

# Events triggering the workflow
on: 
  push:
    branches: 
      - main
  workflow_dispatch:

# Group of jobs to run as part of the workflow
env:
  MY_VAR: "exercise 3 env"
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo GITHUB_TOKEN is ${{secrets.GITHUB_TOKEN}}
          echo MY_VAR is "${{vars.MY_VAR}}"
          echo "${{ env.MY_VAR }}"
      


